"""Writes app/lib/firebase_options.dart from google-services.json (repo root).
If the file is missing, writes a placeholder so the app still builds and shows
a 'setup not finished' screen."""
import json, os, sys
src, out = sys.argv[1], sys.argv[2]
pkg = sys.argv[3] if len(sys.argv) > 3 else ""
vals = dict(apiKey="MISSING", appId="MISSING", messagingSenderId="MISSING", projectId="MISSING", storageBucket="")
if os.path.exists(src):
    g = json.load(open(src))
    info = g.get("project_info", {})
    clients = g.get("client", [])
    c = next((c for c in clients if c.get("client_info", {}).get("android_client_info", {}).get("package_name") == pkg), clients[0] if clients else {})
    vals = dict(
        apiKey=(c.get("api_key") or [{}])[0].get("current_key", ""),
        appId=c.get("client_info", {}).get("mobilesdk_app_id", ""),
        messagingSenderId=info.get("project_number", ""),
        projectId=info.get("project_id", ""),
        storageBucket=info.get("storage_bucket", ""),
    )
    print("Firebase project:", vals["projectId"], "package:", c.get("client_info", {}).get("android_client_info", {}).get("package_name"))
else:
    print("google-services.json not found: building with placeholder Firebase settings")
q = lambda s: "'" + str(s).replace("'", "") + "'"
open(out, "w").write(f"""// GENERATED by tools/make_firebase_options.py - do not edit.
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {{
  static const bool configured = {str(vals['apiKey'] != 'MISSING').lower()};
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
        apiKey: {q(vals['apiKey'])},
        appId: {q(vals['appId'])},
        messagingSenderId: {q(vals['messagingSenderId'])},
        projectId: {q(vals['projectId'])},
        storageBucket: {q(vals['storageBucket'])},
      );
}}
""")
